<a href="https://colab.research.google.com/github/Davidjr2889/Davidjr2889/blob/main/Census_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [3]:
b_c = pd.read_csv('census.csv')

In [7]:
grafico= px.parallel_categories(b_c, dimensions=['occupation', 'relationship'])
grafico.show()

In [10]:
b_c.columns

Index(['age', 'workclass', 'final-weight', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loos', 'hour-per-week', 'native-country',
       'income'],
      dtype='object')

In [8]:
X_c = b_c.iloc[:,0:14].values

In [25]:
X_c[0]

array([39, 7, 77516, ' Bachelors', 13, ' Never-married', ' Adm-clerical',
       ' Not-in-family', ' White', ' Male', 2174, 0, 40, ' United-States'],
      dtype=object)

In [14]:
y_c = b_c.iloc[:, 14].values

In [15]:
y_c

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >5'],
      dtype=object)

TRATAMENTO DE ATRIBUTOS CATEGORICOS

LABEL ENCODER

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [19]:
test = le.fit_transform(X_c[:,1])

In [27]:
X_c[0]

array([39, 7, 77516, 9, 13, 4, 1, 1, 4, 1, 2174, 0, 40, 37], dtype=object)

In [20]:
test

array([7, 6, 4, ..., 4, 4, 2])

In [21]:
lew = LabelEncoder()
lee = LabelEncoder()
lem = LabelEncoder()
leo = LabelEncoder()
ler = LabelEncoder()
lera = LabelEncoder()
les = LabelEncoder()
lec = LabelEncoder()

In [26]:
X_c[:, 1] = lew.fit_transform(X_c[:,1])
X_c[:, 3] = lee.fit_transform(X_c[:,3])
X_c[:, 5] = lem.fit_transform(X_c[:,5])
X_c[:, 6] = leo.fit_transform(X_c[:,6])
X_c[:, 7] = ler.fit_transform(X_c[:,7])
X_c[:, 8] = lera.fit_transform(X_c[:,8])
X_c[:, 9] = les.fit_transform(X_c[:,9])
X_c[:, 13] = lec.fit_transform(X_c[:,13])

In [28]:
X_c

array([[39, 7, 77516, ..., 0, 40, 37],
       [50, 6, 83311, ..., 0, 13, 37],
       [38, 4, 215646, ..., 0, 40, 37],
       ...,
       [23, 4, 193090, ..., 0, 40, 37],
       [64, 4, 151364, ..., 0, 40, 37],
       [70, 2, 88638, ..., 0, 50, 37]], dtype=object)

ONE HOT ENCONDE

In [29]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [30]:
onec= ColumnTransformer(transformers=[('OneHot', OneHotEncoder(),[1,3,5,6,7,8,9,13])], remainder='passthrough')

In [31]:
X_c= onec.fit_transform(X_c).toarray()

In [33]:
X_c[0]

array([0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 1.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e

In [35]:
X_c.shape

(8530, 106)

In [36]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_c = scaler.fit_transform(X_c)

In [38]:
X_c[0]

array([-0.25085523, -0.16831613, -0.25919835, -0.01082807, -1.51273188,
       -0.19191131, -0.2943199 ,  4.96918213, -0.01082807, -0.1719637 ,
       -0.19710485, -0.10612538, -0.06863982, -0.09226403, -0.14430302,
       -0.12823507, -0.18422647, -0.20930391,  2.27130904, -0.10891463,
       -0.69069261, -0.23571684, -0.04197139, -0.13150203, -0.54619202,
       -0.40127061, -0.02865846, -0.91345969, -0.11482362,  1.42070425,
       -0.18320358, -0.17232469, -0.25111913,  2.71192816, -0.0153141 ,
       -0.37058512, -0.37201591, -0.1719637 , -0.20060883, -0.25687254,
       -0.33679618, -0.06418778, -0.38013888, -0.14087925, -0.36565759,
       -0.17340367, -0.23012263, -0.81390661,  1.69729218, -0.17518891,
       -0.43323371, -0.34323307, -0.23096862, -0.10091951, -0.17660565,
       -0.32875526, -0.08556683,  0.41203774, -0.70331763,  0.70331763,
       -0.1386999 , -0.02865846, -0.07034317, -0.05311815, -0.03249945,
       -0.05311815, -0.04598545, -0.02653102, -0.05085078, -0.05

DIVISAO DAS BASES EM TREINAMENTO E TESTE


In [39]:
from sklearn.model_selection import train_test_split

In [40]:
X_c_t, X_c_te, y_c_t, y_c_te = train_test_split(X_c, y_c, test_size=0.25, random_state=0)

In [41]:
X_c_t.shape

(6397, 106)

In [42]:
import pickle

In [ ]:
with open('credi')