<a href="https://colab.research.google.com/github/Davidjr2889/Davidjr2889/blob/main/Risco_de_credito.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB

In [4]:
base_rc = pd.read_csv('/content/risco_credito.csv')

In [5]:
base_rc

historia divida garantias     renda     risco
0           ruim   alta   nenhuma      0_15      alto
1   desconhecida   alta   nenhuma     15_35      alto
2   desconhecida  baixa   nenhuma     15_35  moderado
3   desconhecida  baixa   nenhuma  acima_35      alto
4   desconhecida  baixa   nenhuma  acima_35     baixo
5   desconhecida  baixa  adequada  acima_35     baixo
6           ruim  baixa   nenhuma      0_15      alto
7           ruim  baixa  adequada  acima_35  moderado
8            boa  baixa   nenhuma  acima_35     baixo
9            boa   alta  adequada  acima_35     baixo
10           boa   alta   nenhuma      0_15      alto
11           boa   alta   nenhuma     15_35  moderado
12           boa   alta   nenhuma  acima_35     baixo
13          ruim   alta   nenhuma     15_35      alto

PREPROCESSAMENTO

In [8]:
X_rc = base_rc.iloc[:,0:4].values
X_rc

array([['ruim', 'alta', 'nenhuma', '0_15'],
       ['desconhecida', 'alta', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'adequada', 'acima_35'],
       ['ruim', 'baixa', 'nenhuma', '0_15'],
       ['ruim', 'baixa', 'adequada', 'acima_35'],
       ['boa', 'baixa', 'nenhuma', 'acima_35'],
       ['boa', 'alta', 'adequada', 'acima_35'],
       ['boa', 'alta', 'nenhuma', '0_15'],
       ['boa', 'alta', 'nenhuma', '15_35'],
       ['boa', 'alta', 'nenhuma', 'acima_35'],
       ['ruim', 'alta', 'nenhuma', '15_35']], dtype=object)

In [9]:
y_rc = base_rc.iloc[:,4].values
y_rc

array(['alto', 'alto', 'moderado', 'alto', 'baixo', 'baixo', 'alto',
       'moderado', 'baixo', 'baixo', 'alto', 'moderado', 'baixo', 'alto'],
      dtype=object)

In [10]:
from sklearn.preprocessing import LabelEncoder
le_historia = LabelEncoder()
le_divida = LabelEncoder()
le_garantia = LabelEncoder()
le_renda = LabelEncoder()


In [11]:
X_rc[:,0] = le_historia.fit_transform(X_rc[:,0])
X_rc[:,1] = le_divida.fit_transform(X_rc[:,1])
X_rc[:,2] = le_garantia.fit_transform(X_rc[:,2])
X_rc[:,3] = le_renda.fit_transform(X_rc[:,3])

In [12]:
X_rc

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 1, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [13]:
import pickle
with open('risco_credito.pkl', 'wb') as f:
  pickle.dump([X_rc, y_rc],f)

In [17]:
naive_rc = GaussianNB()
naive_rc.fit(X_rc, y_rc)

GaussianNB()

In [18]:
previsao = naive_rc.predict([[0,0,1,2],[2,0,0,0]])

In [19]:
previsao

array(['baixo', 'moderado'], dtype='<U8')

In [20]:
naive_rc.classes_

array(['alto', 'baixo', 'moderado'], dtype='<U8')

In [21]:
naive_rc.class_count_

array([6., 5., 3.])

In [22]:
naive_rc.class_prior_

array([0.42857143, 0.35714286, 0.21428571])